name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make all
      run: make all -C *
    - name: make clean
      run: make clean -C *
    - name: make fclean
      run: make fclean -C *
    - name: make re
      run: make re -C *
